import { actionMenu, badge, money, table } from "../utils.js";
import { invoiceBalance, invoiceItems, invoicePaid, invoiceStatus, invoiceTotal, state, studentName, ui } from "../state.js";
import { invoicePrint } from "../print/invoice.js";

export function invoices() {
  const action = ui.sectionAction.invoices;
  const selected = state.invoices.find(invoice => invoice.id === ui.selectedInvoiceId) || state.invoices[0];
  if (selected) ui.selectedInvoiceId = selected.id;
  if (!action) return `${actionMenu("Invoices", [
    { section: "invoices", action: "generate", icon: "file-plus", title: "Generate Invoice" },
    { section: "invoices", action: "view", icon: "list", title: "View Issued Invoices" },
    { section: "invoices", action: "payment", icon: "banknote", title: "Record Payment" },
    { section: "invoices", action: "settings", icon: "settings", title: "Invoice Settings" }
  ])}<section class="card no-print"><div class="section-title"><h3>Selected invoice</h3><div class="actions"><button class="btn ghost" onclick="setSectionActionWithHistory('invoices','view')">View Issued Invoices</button><button class="btn primary" onclick="printCurrent()">Print Selected Invoice</button></div></div><p class="muted">${selected ? `${selected.id} - ${studentName(selected.studentId)}` : "No invoice selected yet."}</p></section>${selected ? invoicePrint(selected) : ""}`;
  if (action === "generate") return `<section class="card"><div class="section-title"><h3>Generate Invoice</h3><button class="btn ghost" onclick="navigateBack()">Back</button></div><div class="actions"><button class="btn primary" onclick="openInvoice()">Open guided invoice form</button>${selected ? `<button class="btn ghost" onclick="printCurrent()">Print Selected Invoice</button>` : ""}</div><p class="muted">${selected ? `Selected invoice: ${selected.id}` : "Create an invoice, then print it from here or from issued invoices."}</p></section>${selected ? invoicePrint(selected) : ""}`;
  if (action === "payment") return `<section class="card"><div class="section-title"><h3>Record Payment</h3><button class="btn ghost" onclick="navigateBack()">Back</button></div><div class="actions">${state.invoices.map(invoice => `<button class="btn ghost" onclick="openPayment('${invoice.id}')">${invoice.id}</button>`).join("")}</div></section>`;
  if (action === "settings") return `<section class="card"><div class="section-title"><h3>Invoice Settings</h3><button class="btn ghost" onclick="navigateBack()">Back</button></div><p class="muted">Edit banking details, invoice prefix and print notes in Settings.</p><button class="btn primary" onclick="go('settings')">Open Settings</button></section>`;
  return `<section class="card no-print"><div class="section-title"><h3>Issued invoices</h3><div class="actions"><button class="btn ghost" onclick="navigateBack()">Back</button><button class="btn primary" onclick="printCurrent()">Print Selected Invoice</button></div></div>${table("", ["Invoice", "Student", "Due", "Total", "Paid", "Balance", "Status", ""], state.invoices.map(invoice => [invoice.id, studentName(invoice.studentId), invoice.due, money(invoiceTotal(invoice)), money(invoicePaid(invoice.id)), money(invoiceBalance(invoice)), badge(invoiceStatus(invoice)), `<button class="btn ghost" onclick="selectInvoice('${invoice.id}')">View Preview</button>`]))}</section>${invoicePrint(selected)}`;
}

export function invoiceForm(record = {}) {
  const firstItem = invoiceItems(record.id || "")[0] || {};
  const student = state.students.find(row => row.id === record.studentId) || state.students[0] || {};
  const subjects = student.subjectIds?.length ? state.subjects.filter(subject => student.subjectIds.includes(subject.id)) : state.subjects;
  return `<div class="form-grid"><label class="field"><span>Student</span><select name="studentId" onchange="refreshInvoiceStudentDetails(this.value)">${state.students.map(item => `<option value="${item.id}" ${student.id === item.id ? "selected" : ""}>${item.name}</option>`).join("")}</select></label><label class="field"><span>Guardian</span><input id="invoice-guardian" name="guardian" value="${record.guardian || student.guardian || ""}"></label><label class="field"><span>Parent phone</span><input id="invoice-parent-phone" readonly value="${student.parentPhone || ""}"></label><label class="field"><span>Parent email</span><input id="invoice-parent-email" readonly value="${student.parentEmail || ""}"></label><label class="field"><span>Grade</span><input id="invoice-grade" readonly value="${student.grade || ""}"></label><label class="field"><span>Student ID</span><input id="invoice-student-id" readonly value="${student.id || ""}"></label><label class="field"><span>Location</span><input id="invoice-location" readonly value="${[student.suburb, student.city, student.province].filter(Boolean).join(", ")}"></label><label class="field"><span>Invoice date</span><input name="date" type="date" value="${record.date || ""}"></label><label class="field"><span>Due date</span><input name="due" type="date" value="${record.due || ""}"></label><label class="field"><span>Discount</span><input name="discount" type="number" value="${record.discount || 0}"></label><label class="field"><span>Notes</span><textarea name="notes">${record.notes || ""}</textarea></label></div><h3>Line items</h3><div class="form-grid"><label class="field"><span>Description</span><input name="itemDescription" value="${firstItem.description || ""}"></label><label class="field"><span>Subject</span><select id="invoice-subject" name="itemSubjectId">${subjects.map(subject => `<option value="${subject.id}" ${firstItem.subjectId === subject.id ? "selected" : ""}>${subject.name}</option>`).join("")}</select></label><label class="field"><span>Quantity</span><input name="itemQty" type="number" value="${firstItem.qty || 1}"></label><label class="field"><span>Rate</span><input name="itemRate" type="number" value="${firstItem.rate || state.settings.rate}"></label></div><p class="muted">Student and parent details are populated from the selected student profile.</p>`;
}

export function paymentForm(invoiceId) {
  const invoice = state.invoices.find(row => row.id === invoiceId);
  return `<div class="form-grid"><label class="field"><span>Invoice</span><input name="invoiceId" readonly value="${invoice?.id || ""}"></label><label class="field"><span>Student</span><input readonly value="${studentName(invoice?.studentId)}"></label><label class="field"><span>Date</span><input name="date" type="date"></label><label class="field"><span>Amount</span><input name="amount" type="number"></label><label class="field"><span>Method</span><select name="method"><option>EFT</option><option>Cash</option><option>Card</option></select></label><label class="field"><span>Reference</span><input name="reference"></label></div>`;
}
